name: Syntax Tests

on:
  push:
    paths:
      - '.github/workflows/ci.yml'
      - '**.sublime-syntax'
      - '**/syntax_test*'
      - '**.tmPreferences'
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - '**.sublime-syntax'
      - '**/syntax_test*'
      - '**.tmPreferences'

jobs:
  sublime-text-3:
    name: Syntax tests (ST3)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: SublimeText/syntax-test-action@v2
        with:
          build: 3211
          package_name: ModernFortran
  sublime-text-4:
    name: Syntax tests (ST4)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: SublimeText/syntax-test-action@v2
        with:
          build: 'latest'
          package_name: ModernFortran
